apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bff-sso
  description: "Microservicio backend desarrollado en NestJS para manejar la autenticación y el registro de usuarios."
  tags:
    - nestjs
    - backend
    - sso
    - authentication
spec:
  type: service
  lifecycle: production
  owner: equipo-backend
  providesApis:
    - auth-api
    - login-api
    - signup-api
  links:
    - url: "https://bff-sso.ejemplo.com/auth"
      title: "Auth Endpoint"
    - url: "https://bff-sso.ejemplo.com/login"
      title: "Login Endpoint"
    - url: "https://bff-sso.ejemplo.com/signup"
      title: "Signup Endpoint"
