apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bff-sso
  description: "Microservicio backend desarrollado en NestJS para manejar la autenticación y el registro de usuarios."
  tags:
    - nestjs
    - backend
    - sso
    - authentication
  annotations:
    backstage.io/tech-stack: "NestJS, JWT, OAuth"
    backstage.io/https-url: "https://bff-sso.ejemplo.com:443"
    backstage.io/api-endpoints: "/auth (POST), /login (POST), /signup (POST)"
spec:
  type: service
  lifecycle: production
  owner: equipo-backend
  providesApis:
    - auth-api
    - login-api
    - signup-api
